name: Build and Push Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Backend Maven Build
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build backend with Maven
        working-directory: soltech/project
        run: mvn -B package -DskipTests

      # Build & Push Backend
      - name: Build & Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/soltech-backend:latest \
            -f soltech/project/Dockerfile soltech/project
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/soltech-backend:latest

      # Build frontend
      - name: Build frontend
        working-directory: soltechreact
        run: |
          npm install
          npm run build

      # Build & Push Frontend
      - name: Build & Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/soltech-frontend:latest \
            -f soltechreact/Dockerfile soltechreact
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/soltech-frontend:latest
