name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/soltech-backend:latest -f project/Dockerfile project
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/soltech-backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/soltech-frontend:latest -f project/frontend/Dockerfile project/frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/soltech-frontend:latest
